// Shapes for the build-time content pipeline.
//
// content/linkedin.json  -> LinkedInSnapshot  (generated by `pnpm content:fetch`)
// content/site.json      -> SiteContent       (hand-maintained, site-only data)
//
// src/lib/server/content.ts merges both into the view types at the bottom of this file.

/** "YYYY-MM" or "YYYY", or null when the item is ongoing. */
export type PartialDate = string | null;

export interface LinkedInProfile {
	firstName: string;
	lastName: string;
	headline?: string;
	summary?: string;
	location?: string;
	websites?: string[];
}

export interface LinkedInPosition {
	id: string;
	title: string;
	company: string;
	location?: string;
	description?: string;
	startDate: PartialDate;
	endDate: PartialDate;
}

export interface LinkedInEducation {
	id: string;
	school: string;
	degree?: string;
	notes?: string;
	activities?: string;
	startDate: PartialDate;
	endDate: PartialDate;
}

export interface LinkedInVolunteering {
	id: string;
	role: string;
	organization: string;
	cause?: string;
	description?: string;
	startDate: PartialDate;
	endDate: PartialDate;
}

export interface LinkedInProject {
	id: string;
	title: string;
	description?: string;
	url?: string;
	startDate: PartialDate;
	endDate: PartialDate;
}

export type LanguageProficiency = 'Native' | 'Fluent' | 'Conversational' | 'Basic';

export interface LinkedInLanguage {
	name: string;
	proficiency?: LanguageProficiency;
}

export interface LinkedInCertification {
	name: string;
	authority?: string;
	url?: string;
	startDate: PartialDate;
	endDate: PartialDate;
}

export interface LinkedInHonor {
	title: string;
	description?: string;
	issuedOn: PartialDate;
}

export interface LinkedInCourse {
	name: string;
	number?: string;
}

export interface LinkedInSnapshot {
	/** Where this snapshot came from: "export", "dma" or "seed". */
	source: string;
	fetchedAt: string;
	profile: LinkedInProfile;
	positions: LinkedInPosition[];
	education: LinkedInEducation[];
	volunteering: LinkedInVolunteering[];
	projects: LinkedInProject[];
	skills: string[];
	languages: LinkedInLanguage[];
	certifications: LinkedInCertification[];
	honors: LinkedInHonor[];
	courses: LinkedInCourse[];
}

// ---------------------------------------------------------------------------
// site.json
// ---------------------------------------------------------------------------

export interface PreviewItem {
	title: string;
	link: string;
	/** Site-relative or absolute image URL. */
	image?: string;
}

export type EntryCategory = 'work-experience' | 'education' | 'volunteering';
export type ProjectCategory = 'work-experience' | 'personal' | 'academic' | 'freelance' | 'hackathon';

/** Site-only fields layered over an entry derived from LinkedIn, keyed by its id. */
export interface EntryOverride {
	hidden?: boolean;
	title?: string;
	organization?: string;
	location?: string;
	startDate?: PartialDate;
	endDate?: PartialDate;
	details?: string[];
	technologies?: string[];
	previewItems?: PreviewItem[];
	/** Project ids, resolved against the merged project list. */
	relatedProjects?: string[];
	category?: EntryCategory;
	gpa?: string;
	field?: string;
	degree?: string;
}

/** A project curated on the site. LinkedIn projects with the same id are merged in underneath it. */
export interface SiteProject {
	id: string;
	hidden?: boolean;
	title?: string;
	organization?: string;
	location?: string;
	startDate?: PartialDate;
	endDate?: PartialDate;
	description?: string;
	details?: string[];
	technologies?: string[];
	category?: ProjectCategory;
	githubUrl?: string;
	url?: string;
	showInResume?: boolean;
	previewItems?: PreviewItem[];
}

export interface SiteSkillSection {
	id: string;
	title: string;
	/** Skill names. LinkedIn skills not listed in any section go to `ungroupedSkillsSection`. */
	skills: string[];
}

export interface SiteContent {
	contact: Partial<Contact>;
	entries: Record<string, EntryOverride>;
	projects: SiteProject[];
	skillSections: SiteSkillSection[];
	/** Section that LinkedIn languages (with proficiency) are rendered into. */
	languagesSection?: { id: string; title: string };
	/** Section that LinkedIn skills not grouped above are appended to. Omit to drop them. */
	ungroupedSkillsSection?: { id: string; title: string };
}

// ---------------------------------------------------------------------------
// View types consumed by the pages
// ---------------------------------------------------------------------------

export interface Contact {
	name: string;
	title?: string;
	email: string;
	phone?: string;
	location: string;
	website?: string;
	linkedin?: string;
	github?: string;
}

export interface ResumeEntry {
	kind: 'entry';
	id: string;
	category: EntryCategory;
	title: string;
	organization: string;
	location: string;
	/** ISO "YYYY-MM-DD". */
	startDate: string;
	/** ISO "YYYY-MM-DD", or undefined when ongoing. */
	endDate?: string;
	description?: string;
	details: string[];
	technologies?: string[];
	previewItems?: PreviewItem[];
	relatedProjects?: Project[];
	gpa?: string;
	field?: string;
	degree?: string;
}

export interface Project {
	kind: 'project';
	id: string;
	category: ProjectCategory;
	title: string;
	organization?: string;
	location?: string;
	startDate?: string;
	endDate?: string;
	showInResume: boolean;
	description?: string;
	details: string[];
	technologies?: string[];
	githubUrl?: string;
	url?: string;
	previewItems?: PreviewItem[];
}

export interface SkillSection {
	id: string;
	title: string;
	skills: { id: string; name: string; proficiency?: LanguageProficiency }[];
}

/** Extra LinkedIn data that has no section on the site yet. */
export interface ContentExtras {
	certifications: LinkedInCertification[];
	honors: LinkedInHonor[];
	courses: LinkedInCourse[];
}
